# Generated by Django 3.2.5 on 2021-09-25 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('firstname', models.CharField(max_length=34)),
                ('lastname', models.CharField(max_length=34)),
                ('username', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=34)),
                ('address', models.CharField(max_length=34)),
                ('high_qualification', models.IntegerField(choices=[(1, 'Matric'), (2, 'Diploma'), (3, 'Bachelor'), (4, 'Masters')], default=1)),
                ('specialization', models.CharField(max_length=30)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('email', models.EmailField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('compay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('firstname', models.CharField(max_length=34)),
                ('lastname', models.CharField(max_length=34)),
                ('username', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=34)),
                ('address', models.CharField(max_length=34)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
