# Generated by Django 3.2.5 on 2021-09-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210925_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
