# Generated by Django 3.2.5 on 2021-09-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_careerinfo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerinfo',
            name='slug',
        ),
    ]
